# -*- coding: utf-8 -*-
"""Chisquare-test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KEbjULBZgFkUvM0gDCTvsIbW5mMoCOj1
"""

import numpy as np
import scipy.stats as stats

# Observed data from the contingency table
observedData = np.array([
    [50, 70],  # Very Satisfied
    [80, 100], # Satisfied
    [60, 90],  # Neutral
    [30, 50],  # Unsatisfied
    [20, 50]   # Very Unsatisfied
])

# 1: State Hypotheses

# 2: Compute the Chi-Square Statistic
rowTotals = observedData.sum(axis=1)
colTotals = observedData.sum(axis=0)
grandTotal = observedData.sum()

# Calculate expected frequencies
expected = np.outer(rowTotals, colTotals) / grandTotal

# Calculate Chi-Square statistic
chiSquareStat = ((observedData - expected) ** 2 / expected).sum()

# 3: Degrees of Freedom and Critical Value calculation
df = (observedData.shape[0] - 1) * (observedData.shape[1] - 1)
criticalValue = stats.chi2.ppf(0.95, df)

# 4: Make a Decision for the requirement
if chiSquareStat > criticalValue:
    takeDecision = "Reject the null hypothesis: There is a significant association."
else:
    takeDecision = "Fail to reject the null hypothesis: No significant association."

# Output results
print("Chi-Square Statistic:", chiSquareStat)
print("Degrees of Freedom:", df)
print("Critical Value:", criticalValue)
print("Decision Take:", takeDecision)

