# -*- coding: utf-8 -*-
"""Hypothesis testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HL3SGh3-UsEKQ8pkqLURFmiDenZxLGCS
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import math
from scipy.stats import norm

# Data Provided
sampleMean = 3050  # Sample mean weekly cost as our requirement
theoreticalMean = 1000 + 5 * 600  # To Get theoretical mean weekly cost
stdDev = 5 * 25  # This is the standard deviation of weekly costs
sampleSize = 25  # As our requirment sample size
alpha = 0.05  # This is the significance level of the requirement

# 1: Calculate the test statistic value
standardError = stdDev / math.sqrt(sampleSize)
testValue = (sampleMean - theoreticalMean) / standardError

# 2: Preparing the critical value
criticalValue = norm.ppf(1 - alpha)

# 3: Comparing the test statistic with the critical value
if testValue > criticalValue:
    HypothesisDecision = "Null hypothesis(H0) is rejected"
else:
    HypothesisDecision = "Alternative Hypothesis (H1) is rejected"

# Show the results
print(f"Theoretical Weekly Cost (μ): {theoreticalMean}")
print(f"Sample Mean Weekly Cost (ˉx): {sampleMean}")
print(f"Standard Error: {standardError:.2f}")
print(f"Test Value (t): {testValue:.2f}")
print(f"Critical Value (Zα): {criticalValue:.2f}")
print(f"Hypothesis Decision: {HypothesisDecision}")